begin;
select plan(17);
-- Every fixture and temporary status change rolls back, including real pending jobs.
update public.local_backup_runs set status='failed',finished_at=now() where status in ('queued','running');
update public.profiles set status='inactive',disabled_at=null where erp_role='owner';
create temporary table bt(owner_id uuid,owner_session uuid,admin_id uuid,admin_session uuid,job uuid);
insert into bt select gen_random_uuid(),gen_random_uuid(),gen_random_uuid(),gen_random_uuid(),null;
insert into auth.users(id,email,role,aud,email_confirmed_at) select owner_id,'backup.owner.test@gmail.com','authenticated','authenticated',now() from bt;
insert into public.profiles(id,employee_name,position_id,department,erp_role,username,contact,avatar_path)
select owner_id,'Backup Test Owner',(select id from public.positions where erp_role_code='owner'),'Test','owner','backup.owner.test@gmail.com','test',owner_id||'/photo.png' from bt;
insert into auth.sessions(id,user_id,created_at,updated_at) select owner_session,owner_id,now(),now() from bt;
select set_config('request.jwt.claims',jsonb_build_object('sub',owner_id,'role','authenticated','session_id',owner_session)::text,true) from bt;
insert into auth.users(id,email,role,aud,email_confirmed_at,raw_app_meta_data) select admin_id,'backup.admin.test@gmail.com','authenticated','authenticated',now(),jsonb_build_object('provisioned_by',owner_id) from bt;
select public.provision_employee(admin_id,'admin','Backup Admin','Office Manager','Test','backup.admin.test@gmail.com','test',admin_id||'/photo.png') from bt;
insert into auth.sessions(id,user_id,created_at,updated_at) select admin_session,admin_id,now(),now() from bt;
update public.profiles set page_access='{}',action_access='{}',individual_pages='{}',individual_actions='{}' where id=(select admin_id from bt);
select ok(not has_function_privilege('anon','public.request_local_backup(text)','execute'),'anonymous backup denied');
select ok(not has_function_privilege('authenticated','private.assert_local_backup_authority(uuid)','execute'),'worker check is not a client API');
select ok(not has_table_privilege('authenticated','public.local_backup_runs','update'),'clients cannot spoof verification');
select throws_ok($$select public.request_local_backup(' ')$$,'P0001','Backup reason required','reason required');
update bt set job=public.request_local_backup('Verify encrypted local backup');
select is((select requester_session from public.local_backup_runs where id=(select job from bt)),(select owner_session from bt),'request binds the authenticated session');
select throws_ok($$select public.request_local_backup('Duplicate')$$,'P0001','A local backup is already pending','second pending backup denied');
select is((select count(*) from public.audit_events where action='Local backup requested' and entity_id=(select job::text from bt)),1::bigint,'request audited');
update public.local_backup_runs set status='running' where id=(select job from bt);
select lives_ok($$select private.assert_local_backup_authority(job) from bt$$,'worker validates live Owner authority');
update public.profiles set status='locked' where id=(select owner_id from bt);
select throws_ok($$select private.assert_local_backup_authority(job) from bt$$,'42501','Permission denied','lock between request and execution blocks capture');
update public.profiles set status='active' where id=(select owner_id from bt);
update public.local_backup_runs set status='failed',finished_at=now() where id=(select job from bt);
select set_config('request.jwt.claims',jsonb_build_object('sub',admin_id,'role','authenticated','session_id',admin_session)::text,true) from bt;
select throws_ok($$select public.request_local_backup('Unscoped Admin')$$,'42501','Permission denied','Admin needs explicit backup action');
set local role authenticated;
select is((select count(*) from public.local_backup_runs),0::bigint,'Admin without page cannot read backups');
reset role;
update public.profiles set individual_pages='{"backups":true}',individual_actions='{"Backup & Restore":["create"]}' where id=(select admin_id from bt);
update bt set job=public.request_local_backup('Scoped Admin backup');
select is((select requester_id from public.local_backup_runs where id=(select job from bt)),(select admin_id from bt),'scoped Admin can request');
update public.local_backup_runs set status='running' where id=(select job from bt);
select lives_ok($$select private.assert_local_backup_authority(job) from bt$$,'worker honors additional grants');
update public.profiles set individual_actions='{}' where id=(select admin_id from bt);
select throws_ok($$select private.assert_local_backup_authority(job) from bt$$,'42501','Permission denied','revoked action blocks worker');
update public.profiles set individual_actions='{"Backup & Restore":["create"]}' where id=(select admin_id from bt);
delete from auth.sessions where id=(select admin_session from bt);
select throws_ok($$select private.assert_local_backup_authority(job) from bt$$,'42501','Permission denied','expired session blocks worker');
select set_config('request.jwt.claims',jsonb_build_object('sub',owner_id,'role','authenticated','session_id',owner_session)::text,true) from bt;
update public.local_backup_runs set status='queued' where id=(select job from bt);
select public.fail_queued_local_backup(job) from bt;
select is((select status from public.local_backup_runs where id=(select job from bt)),'queued','launch compensation cannot change another requester job');
set local role authenticated;
select throws_ok($$update public.local_backup_runs set status='verified'$$,'42501','permission denied for table local_backup_runs','direct verified status mutation denied');
reset role;
select finish();
rollback;
