begin;
select no_plan();
-- Transaction-only fixture: every account and mutation below is rolled back.
update public.profiles set status='inactive',disabled_at=null where erp_role='owner';
create temporary table sf(o uuid,os uuid,a uuid,axs uuid,b uuid,bs uuid,u uuid,us uuid,s uuid,req bigint,ver integer,token uuid,payload jsonb,result jsonb);
insert into sf select gen_random_uuid(),gen_random_uuid(),gen_random_uuid(),gen_random_uuid(),gen_random_uuid(),gen_random_uuid(),gen_random_uuid(),gen_random_uuid(),null,null,0,gen_random_uuid(),
'{"city":"Yangon","legalName":"Supplier SQL fixture","contact":{"name":"U Ba","phone":"0912345678","email":"supplier@example.com"},"address":{"addressLine":"Main Road","cityTownship":"Hlaing","stateRegion":"Yangon","country":"Myanmar"},"agreement":{"currencyCode":"CNY","currencyName":"Chinese Yuan","titles":[]},"formula":{"steps":[]},"sampleBasePrice":100,"sampleQuantity":2,"sampleDeposit":20}',null;
insert into auth.users(id,email,role,aud,email_confirmed_at)
select o,'supplier.owner.test@gmail.com','authenticated','authenticated',now() from sf union all select a,'supplier.admin.test@gmail.com','authenticated','authenticated',now() from sf union all select b,'supplier.checker.test@gmail.com','authenticated','authenticated',now() from sf union all select u,'supplier.staff.test@gmail.com','authenticated','authenticated',now() from sf;
insert into public.profiles(id,employee_name,position_id,department,erp_role,username,contact,avatar_path)
select id,name,(select id from public.positions where erp_role_code=role),'Test',role,email,'test',id||'/photo.png' from
(select o id,'Supplier Owner' name,'owner' role,'supplier.owner.test@gmail.com' email from sf union all select a,'Supplier Admin','admin','supplier.admin.test@gmail.com' from sf union all select b,'Supplier Checker','admin','supplier.checker.test@gmail.com' from sf union all select u,'Supplier Staff','sales','supplier.staff.test@gmail.com' from sf) f;
update public.profiles set page_access='{"suppliers":true,"approvals":true}',action_access='{"Suppliers & Commercials":["view","create","edit","submit","approve","import","export"]}' where id in (select a from sf union all select b from sf);
update public.profiles set page_access='{}',action_access='{}',individual_pages='{}',individual_actions='{}' where id=(select u from sf);
insert into auth.sessions(id,user_id,created_at,updated_at) select os,o,now(),now() from sf union all select axs,a,now(),now() from sf union all select bs,b,now(),now() from sf union all select us,u,now(),now() from sf;
select set_config('request.jwt.claims',jsonb_build_object('sub',a,'role','authenticated','session_id',axs)::text,true) from sf;
select ok(not has_function_privilege('anon','public.save_supplier_package(uuid,integer,jsonb,text,boolean,uuid)','execute'),'anon cannot create Supplier');
select ok(not has_table_privilege('authenticated','public.supplier_packages','INSERT'),'client cannot forge package');
select ok(not has_table_privilege('authenticated','public.suppliers','UPDATE'),'client cannot activate Supplier');
select ok((select bool_and(relrowsecurity) from pg_class where oid in ('public.suppliers'::regclass,'public.supplier_packages'::regclass)),'Supplier RLS enabled');
select is(public.generate_supplier_code('Yangon'),'SUP-YGN-00001','city code uses YGN');
update sf set result=public.save_supplier_package(null,0,payload,'Initial draft',false,token);
update sf set s=(result->>'id')::uuid,ver=(result->>'version')::integer;
select is((select status from public.suppliers where id=(select s from sf)),'draft','saved draft is durable');
select is((select public.save_supplier_package(null,0,payload,'Initial draft',false,token) from sf),(select result from sf),'same command replay is idempotent');
select is((select count(*) from public.supplier_packages where supplier_id=(select s from sf)),1::bigint,'retry created one package');
select throws_ok($$select public.save_supplier_package(null,0,payload,'Changed token input',false,token) from sf$$,'P0001','Command token was already used with different input','token cannot be reused for another command');
select throws_ok($$select public.save_supplier_package(s,0,payload,'Stale',false,gen_random_uuid()) from sf$$,'P0001','Supplier changed; reload before saving','stale concurrent editor rejected');
select throws_ok($$select public.save_supplier_package(null,0,payload,'Duplicate',false,gen_random_uuid()) from sf$$,'P0001','Supplier Legal Name already exists in this city','database blocks duplicate name');
update sf set result=public.save_supplier_package(s,ver,payload,'Submit package',true,gen_random_uuid());
update sf set req=(result->>'requestId')::bigint,ver=(result->>'version')::integer;
select is((select status from public.approval_requests where id=(select req from sf)),'pending','one-package request reaches real queue');
select is((select request_type from public.approval_requests where id=(select req from sf)),'supplier_package','queue has correct request type');
select ok((select active_package_id is null from public.suppliers where id=(select s from sf)),'no activation before approval');
select throws_ok($$select public.save_supplier_package(s,ver,payload,'Pending edit',false,gen_random_uuid()) from sf$$,'P0001','Withdraw the pending request before editing','pending is locked');
select throws_ok($$select public.decide_supplier_package(req,'approve','Self approval') from sf$$,'P0001','Only Owner may self-approve','Admin creator cannot self-approve');
select set_config('request.jwt.claims',jsonb_build_object('sub',u,'role','authenticated','session_id',us)::text,true) from sf;
select throws_ok($$select public.decide_supplier_package(req,'approve','Unauthorized') from sf$$,'42501','Supplier permission denied','unauthorized approval denied');
set local role authenticated;
select is((select count(*) from public.supplier_packages),0::bigint,'unauthorized user cannot read package');
reset role;
select set_config('request.jwt.claims',jsonb_build_object('sub',b,'role','authenticated','session_id',bs)::text,true) from sf;
select lives_ok($$select public.decide_supplier_package(req,'approve','Independent approval') from sf$$,'authorized independent Admin approves');
select is((select status from public.suppliers where id=(select s from sf)),'active','approval activates Supplier');
select is((select count(*) from public.supplier_commercial_agreements where supplier_id=(select s from sf) and status='active'),1::bigint,'one active Agreement');
select is((select count(*) from public.supplier_financial_formulas where supplier_id=(select s from sf) and status='active'),1::bigint,'one active Formula');
select throws_ok($$select public.decide_supplier_package(req,'approve','Replay') from sf$$,'P0001','Supplier request is not pending','approval replay rejected');
select throws_ok($$update public.supplier_packages set payload=jsonb_set(payload,'{legalName}','"Tampered"') where supplier_id=(select s from sf)$$,'P0001','Submitted Supplier package is immutable','approved snapshot cannot change');
select set_config('request.jwt.claims',jsonb_build_object('sub',a,'role','authenticated','session_id',axs)::text,true) from sf;
update sf set ver=(select edit_version from public.suppliers where id=s),payload=jsonb_set(payload,'{legalName}','"Supplier revised name"');
update sf set result=public.save_supplier_package(s,ver,payload,'Revision draft',false,gen_random_uuid());
select is((select legal_name from public.suppliers where id=(select s from sf)),'Supplier SQL fixture','draft revision leaves Active facts unchanged');
select is((select count(*) from public.supplier_packages where supplier_id=(select s from sf) and status='active'),1::bigint,'active remains effective during revision');
update sf set ver=(result->>'version')::integer;
update sf set result=public.save_supplier_package(s,ver,payload,'Submit revision',true,gen_random_uuid());
update sf set req=(result->>'requestId')::bigint;
select set_config('request.jwt.claims',jsonb_build_object('sub',o,'role','authenticated','session_id',os)::text,true) from sf;
select lives_ok($$select public.decide_supplier_package(req,'reject','Reject revision') from sf$$,'Owner rejects revision');
select is((select legal_name from public.suppliers where id=(select s from sf)),'Supplier SQL fixture','rejection leaves previous Active facts');
update sf set ver=(select edit_version from public.suppliers where id=s);
update sf set result=public.save_supplier_package(s,ver,payload,'Owner revision',true,gen_random_uuid());
update sf set req=(result->>'requestId')::bigint;
select lives_ok($$select public.decide_supplier_package(req,'approve','Owner exception') from sf$$,'Owner self-approval exception preserved');
select is((select legal_name from public.suppliers where id=(select s from sf)),'Supplier revised name','approved revision updates Active facts');
select is((select count(*) from public.supplier_packages where supplier_id=(select s from sf) and status='archived'),1::bigint,'old approved package archived not deleted');
select is((select count(*) from public.supplier_packages where supplier_id=(select s from sf) and status='rejected'),1::bigint,'rejected revision retained');
select is((select count(*) from public.supplier_commercial_agreements where supplier_id=(select s from sf) and status='active'),1::bigint,'still exactly one Active Agreement after revision');
select is((select count(*) from public.supplier_financial_formulas where supplier_id=(select s from sf) and status='active'),1::bigint,'still exactly one Active Formula after revision');
select ok((select count(*)>0 from public.audit_events where entity_type='supplier' and entity_id=(select s::text from sf)),'durable audit recorded');
select ok((select count(*)>0 from public.notifications where approval_request_id=(select req from sf)),'durable notification recorded');
select is(private.validate_supplier_payload((select payload from sf),true)->>'grandTotal','180.00','zero-title package formula agrees with preview');
select throws_ok($$select private.validate_supplier_payload(jsonb_set(payload,'{sampleDeposit}','201'),true) from sf$$,'P0001','Deposit cannot exceed Sub Total','invalid Deposit rejected server-side');
select throws_ok($$select private.validate_supplier_payload(jsonb_set(payload,'{agreement,currencyName}','"Wrong"'),true) from sf$$,'P0001','Invalid currency code or name','currency mapping checked server-side');
select set_config('request.jwt.claims',jsonb_build_object('sub',a,'role','authenticated','session_id',gen_random_uuid())::text,true) from sf;
select throws_ok($$select public.save_supplier_package(null,0,payload,'Forged session',false,gen_random_uuid()) from sf$$,'42501','Supplier permission denied','forged session denied');
select * from finish();
rollback;
