begin;
select plan(29);
update public.profiles set status='inactive',disabled_at=null where erp_role='owner';
delete from private.login_attempts;
create temporary table la(owner_id uuid default gen_random_uuid(),peer uuid default gen_random_uuid(),session_id uuid default gen_random_uuid(),ticket uuid);
insert into la default values;
insert into auth.users(id,email,role,aud,email_confirmed_at)
select owner_id,'admission.owner.test@gmail.com','authenticated','authenticated',now() from la
union all select peer,'admission.peer.test@gmail.com','authenticated','authenticated',now() from la;
insert into public.profiles(id,employee_name,position_id,department,erp_role,username,contact,avatar_path)
select owner_id,'Admission Owner',(select id from public.positions where erp_role_code='owner'),'Test','owner','admission.owner.test@gmail.com','test',owner_id||'/photo.png' from la;
insert into auth.sessions(id,user_id,created_at,updated_at) select session_id,owner_id,clock_timestamp(),clock_timestamp() from la;
select ok(not has_function_privilege('authenticated','public.reserve_login_attempt(text)','execute'),'clients cannot reserve trusted attempts');
select ok(not has_function_privilege('service_role','public.record_login_attempt(text,boolean,uuid)','execute'),'legacy admission cannot bypass throttle');
select ok(not has_table_privilege('service_role','private.login_attempts','select'),'attempt ledger is private');
select set_config('request.jwt.claims',jsonb_build_object('sub',owner_id,'role','authenticated','session_id',session_id)::text,true) from la;
select ok(not private.is_active_user(),'raw provider login without ERP admission has no data access');
select set_config('request.jwt.claims','{"role":"service_role"}',true);
update la set ticket=public.reserve_login_attempt(' ADMISSION.OWNER.TEST@gmail.com '),session_id=gen_random_uuid();
select ok((select ticket is not null from la),'server reserves normalized identifier before Auth');
insert into auth.sessions(id,user_id,created_at,updated_at) select session_id,owner_id,clock_timestamp(),clock_timestamp() from la;
select ok(public.complete_login_attempt(ticket,'success',session_id),'new provider session is admitted once') from la;
select set_config('request.jwt.claims',jsonb_build_object('sub',owner_id,'role','authenticated','session_id',session_id)::text,true) from la;
select ok(private.is_active_user(),'admitted active account session can access ERP');
select set_config('request.jwt.claims','{"role":"service_role"}',true);
select ok(not public.complete_login_attempt(ticket,'success',session_id),'consumed ticket cannot replay admission') from la;
select set_config('request.jwt.claims',jsonb_build_object('sub',owner_id,'role','authenticated','session_id',session_id)::text,true) from la;
select public.end_my_session();
select ok(not private.is_active_user(),'logout remains effective before provider cleanup');
select set_config('request.jwt.claims','{"role":"service_role"}',true);
update la set ticket=public.reserve_login_attempt('admission.owner.test@gmail.com');
select ok(not public.complete_login_attempt(ticket,'success',session_id),'fresh ticket cannot revive old/revoked provider session') from la;
update la set ticket=public.reserve_login_attempt('admission.owner.test@gmail.com'),session_id=gen_random_uuid();
insert into auth.sessions(id,user_id,created_at,updated_at) select session_id,peer,clock_timestamp(),clock_timestamp() from la;
select ok(not public.complete_login_attempt(ticket,'success',session_id),'session for another identity is rejected') from la;
update la set ticket=public.reserve_login_attempt('admission.owner.test@gmail.com');
select ok(not public.complete_login_attempt(ticket,'success',null),'missing session ID fails closed') from la;
select public.complete_login_attempt(public.reserve_login_attempt('admission.owner.test@gmail.com'),'service_failure');
select is((select failed_login_attempts from public.profiles where id=(select owner_id from la)),0::smallint,'provider outage never increments wrong-password count');
select public.complete_login_attempt(public.reserve_login_attempt('admission.owner.test@gmail.com'),'invalid_credentials') from generate_series(1,4);
select is((select failed_login_attempts from public.profiles where id=(select owner_id from la)),4::smallint,'four distinct wrong attempts are counted');
select is((select count(*) from public.audit_events where entity_id=(select owner_id::text from la) and action='Password sign-in failed'),4::bigint,'each wrong attempt remains audited');
select public.complete_login_attempt(public.reserve_login_attempt('admission.owner.test@gmail.com'),'invalid_credentials');
select is((select status from public.profiles where id=(select owner_id from la)),'locked','fifth wrong password locks account');
select is((select count(*) from public.device_sessions where profile_id=(select owner_id from la) and status in ('active','pending')),0::bigint,'lock closes all admitted sessions');
select set_config('request.jwt.claims',jsonb_build_object('sub',owner_id,'role','authenticated','session_id',session_id)::text,true) from la;
select ok(not private.is_active_user(),'locked account cannot use retained JWT');
select set_config('request.jwt.claims','{"role":"service_role"}',true);
update la set ticket=public.reserve_login_attempt('admission.owner.test@gmail.com'),session_id=gen_random_uuid();
insert into auth.sessions(id,user_id,created_at,updated_at) select session_id,owner_id,clock_timestamp(),clock_timestamp() from la;
select ok(not public.complete_login_attempt(ticket,'success',session_id),'provider success cannot unlock a locked account') from la;
delete from private.login_attempts;
select is((select count(public.reserve_login_attempt('unknown.test@gmail.com')) from generate_series(1,15)),15::bigint,'unknown identifiers use same fifteen-attempt budget');
select is(public.reserve_login_attempt('unknown.test@gmail.com'),null::uuid,'sixteenth reservation is throttled before Auth');
select ok(public.reserve_login_attempt('another.test@gmail.com') is not null,'one identifier does not exhaust another identifier budget');
update la set ticket=public.reserve_login_attempt('stale.test@gmail.com');
update private.login_attempts set created_at=now()-interval '16 minutes' where id=(select ticket from la);
select ok(not public.complete_login_attempt(ticket,'invalid_credentials'),'stale reservations cannot count or admit') from la;
delete from private.login_attempts;
insert into private.login_attempts(username) select 'spray-'||n||'@gmail.com' from generate_series(1,120) n;
select is(public.reserve_login_attempt('new.test@gmail.com'),null::uuid,'global limit prevents identifier spraying');
update private.login_attempts set created_at=now()-interval '16 minutes';
select ok(public.reserve_login_attempt('new.test@gmail.com') is not null,'expired throttle budget can recover');
select ok(not has_function_privilege('authenticated','public.complete_login_attempt(uuid,text,uuid)','execute'),'clients cannot forge provider results');
select ok(not public.complete_login_attempt(null,'success'),'missing ticket cannot admit');
select throws_ok($$select public.complete_login_attempt(null,null)$$,'P0001','Invalid outcome','null result cannot bypass validation');
select is((select count(*) from private.login_attempts),1::bigint,'old ephemeral reservations are pruned without deleting audit history');
select * from finish();
rollback;
