begin;
select plan(23);
update public.profiles set status='inactive',disabled_at=null where erp_role='owner';
delete from private.login_attempts;
create temporary table td(owner_id uuid default gen_random_uuid(),s1 uuid default gen_random_uuid(),s2 uuid default gen_random_uuid(),s3 uuid default gen_random_uuid(),t1 uuid,t2 uuid,t3 uuid,request_id bigint);
insert into td default values;
insert into auth.users(id,email,role,aud,email_confirmed_at) select owner_id,'device.owner.test@gmail.com','authenticated','authenticated',now() from td;
insert into public.profiles(id,employee_name,position_id,department,erp_role,username,contact,avatar_path)
select owner_id,'Device Owner',(select id from public.positions where erp_role_code='owner'),'Test','owner','device.owner.test@gmail.com','test',owner_id||'/photo.png' from td;
select set_config('request.jwt.claims','{"role":"service_role"}',true);
update td set t1=public.reserve_login_attempt('device.owner.test@gmail.com'),t2=public.reserve_login_attempt('device.owner.test@gmail.com'),t3=public.reserve_login_attempt('device.owner.test@gmail.com');
insert into auth.sessions(id,user_id,created_at,updated_at) select s1,owner_id,clock_timestamp(),clock_timestamp() from td union all select s2,owner_id,clock_timestamp()+interval '1 second',clock_timestamp()+interval '1 second' from td union all select s3,owner_id,clock_timestamp()+interval '2 seconds',clock_timestamp()+interval '2 seconds' from td;
select is(public.complete_login_attempt(t1,'success',s1),'admitted','first device admitted') from td;
select is(public.complete_login_attempt(t2,'success',s2),'admitted','second device admitted') from td;
select is((select count(*) from public.device_sessions where profile_id=owner_id and status='active'),2::bigint,'two active devices are allowed') from td;
select is(public.complete_login_attempt(t3,'success',s3),'pending','third device waits for approval') from td;
select ok((select status='pending' and deadline_at is not null from public.approval_requests where request_type='device_login' and requester_id=(select owner_id from td)),'third-device request has one-day deadline');
update td set request_id=(select id from public.approval_requests where request_type='device_login' and requester_id=owner_id and status='pending'),t3=public.reserve_login_attempt('device.owner.test@gmail.com');
select is(public.complete_login_attempt(t3,'success',s3),'pending','same third device request is idempotent') from td;
select ok(not exists(select 1 from public.device_sessions where id=(select s3 from td)),'pending provider session has no ERP admission');
select set_config('request.jwt.claims',jsonb_build_object('sub',owner_id,'role','authenticated','session_id',s3)::text,true) from td;
select is(public.my_login_approval_status(),'pending','pending provider session can poll approval without ERP data access');
select ok(not private.is_active_user(),'pending provider session remains blocked from ERP data');
select ok(not has_function_privilege('anon','public.decide_device_login(bigint,boolean,text)','execute'),'anonymous cannot decide device approval');
select set_config('request.jwt.claims',jsonb_build_object('sub',owner_id,'role','authenticated','session_id',s1)::text,true) from td;
select throws_ok($$select public.decide_device_login(request_id,true,'') from td$$,'P0001','Decision reason required','approval reason is mandatory');
select public.decide_device_login(request_id,true,'Replace the oldest approved device') from td;
select is((select status from public.approval_requests where id=(select request_id from td)),'approved','Owner approval is recorded');
select is((select count(*) from public.device_sessions where profile_id=(select owner_id from td) and status='active'),2::bigint,'approval keeps the two-device limit');
select ok((select status='logged_out' and ended_reason='Approved third-device replacement' from public.device_sessions where id=(select s1 from td)),'oldest active session is logged out');
select ok((select status='active' from public.device_sessions where id=(select s3 from td)),'approved third device is admitted');
select set_config('request.jwt.claims',jsonb_build_object('sub',owner_id,'role','authenticated','session_id',s3)::text,true) from td;
select is(public.my_login_approval_status(),'admitted','same pending session observes approval without a new login');
select set_config('request.jwt.claims',jsonb_build_object('sub',owner_id,'role','authenticated','session_id',s3)::text,true) from td;
select ok(private.is_active_user(),'approved third-device session can access ERP');
select set_config('request.jwt.claims',jsonb_build_object('sub',owner_id,'role','authenticated','session_id',s1)::text,true) from td;
select ok(not private.is_active_user(),'replaced oldest session cannot access ERP');
select set_config('request.jwt.claims','{"role":"service_role"}',true);
update td set t3=gen_random_uuid();
update td set t1=public.reserve_login_attempt('device.owner.test@gmail.com');
insert into auth.sessions(id,user_id,created_at,updated_at) select t3,owner_id,clock_timestamp(),clock_timestamp() from td;
select is(public.complete_login_attempt(t1,'success',t3),'pending','a further third device again requires approval') from td;
select is((select count(*) from public.device_sessions where profile_id=owner_id and status='active'),2::bigint,'replacement login never exceeds two active devices') from td;
select set_config('request.jwt.claims',jsonb_build_object('sub',owner_id,'role','authenticated','session_id',s3)::text,true) from td;
select throws_ok($$select public.decide_device_login(request_id,true,'Replay') from td$$,'P0001','Request is not pending','approved request cannot be replayed');
select ok(exists(select 1 from public.audit_events where action='Device sign-in approved' and approval_request_id=(select request_id from td)),'approval is audited');
select ok(exists(select 1 from public.notifications where approval_request_id=(select request_id from td)),'requester is notified');
select * from finish();
rollback;
