begin;
select plan(11);
update public.profiles set status='inactive',disabled_at=null where erp_role='owner';
delete from private.login_attempts;
create temporary table ir(owner_id uuid default gen_random_uuid(),old_session uuid default gen_random_uuid(),current_session uuid default gen_random_uuid(),new_session uuid default gen_random_uuid(),ticket uuid,request_id bigint);
insert into ir default values;
insert into auth.users(id,email,role,aud,email_confirmed_at) select owner_id,'idle.owner.test@gmail.com','authenticated','authenticated',now() from ir;
insert into public.profiles(id,employee_name,position_id,department,erp_role,username,contact,avatar_path)
select owner_id,'Idle Owner',(select id from public.positions where erp_role_code='owner'),'Test','owner','idle.owner.test@gmail.com','test',owner_id||'/photo.png' from ir;
insert into auth.sessions(id,user_id,created_at,updated_at) select old_session,owner_id,now()-interval '8 days',now()-interval '8 days' from ir union all select current_session,owner_id,clock_timestamp(),clock_timestamp() from ir;
insert into public.device_sessions(id,profile_id,device_fingerprint_hash,device_label,started_at,last_seen_at) select old_session,owner_id,extensions.digest(old_session::text,'sha256'),'Old laptop',now()-interval '8 days',now()-interval '8 days' from ir union all select current_session,owner_id,extensions.digest(current_session::text,'sha256'),'Current phone',now(),now() from ir;
select set_config('request.jwt.claims','{"role":"service_role"}',true);
update ir set ticket=public.reserve_login_attempt('idle.owner.test@gmail.com'),new_session=gen_random_uuid();
insert into auth.sessions(id,user_id,created_at,updated_at) select new_session,owner_id,clock_timestamp(),clock_timestamp() from ir;
select is(public.complete_login_attempt(ticket,'success',new_session),'pending','idle account login waits for reapproval') from ir;
select ok((select status='logged_out' and ended_reason='Idle seven-day reapproval' from public.device_sessions where id=ir.old_session),'seven-day idle device is logged out') from ir;
select ok((select requires_login_approval from public.profiles where id=owner_id),'profile is fenced until approval') from ir;
select ok((select proposed_data->>'reasonCode'='idle-seven-day' from public.approval_requests where request_type='device_login' and requester_id=ir.owner_id and status='pending'),'request records idle reason') from ir;
update ir set request_id=(select id from public.approval_requests where request_type='device_login' and requester_id=owner_id and status='pending');
select set_config('request.jwt.claims',jsonb_build_object('sub',owner_id,'role','authenticated','session_id',current_session)::text,true) from ir;
select throws_ok($$select public.decide_device_login(request_id,true,' ') from ir$$,'P0001','Decision reason required','idle approval needs a reason');
select public.decide_device_login(request_id,true,'Reapprove after seven-day idle review') from ir;
select is((select status from public.approval_requests where id=(select request_id from ir)),'approved','idle approval is recorded');
select ok((select not requires_login_approval from public.profiles where id=owner_id),'approval clears login fence') from ir;
select ok((select status='active' from public.device_sessions where id=ir.new_session),'approved session is admitted') from ir;
select is((select count(*) from public.device_sessions where profile_id=owner_id and status='active'),1::bigint,'idle replacement stays within two-device limit') from ir;
select ok(exists(select 1 from public.audit_events where action='Device sign-in approved' and approval_request_id=(select request_id from ir)),'idle decision is audited');
select ok(exists(select 1 from public.notifications where approval_request_id=(select request_id from ir)),'idle requester is notified');
select * from finish();
rollback;
