begin;
select plan(14);
update public.profiles set status='inactive',disabled_at=null where erp_role='owner';
create temporary table pw(owner_id uuid default gen_random_uuid(),staff_id uuid default gen_random_uuid(),owner_session uuid default gen_random_uuid(),staff_session uuid default gen_random_uuid(),operation uuid);
insert into pw default values;
insert into auth.users(id,email,role,aud,email_confirmed_at) select owner_id,'password.owner.test@gmail.com','authenticated','authenticated',now() from pw union all select staff_id,'password.staff.test@gmail.com','authenticated','authenticated',now() from pw;
insert into public.profiles(id,employee_name,company_position,position_id,department,erp_role,username,contact,avatar_path) select owner_id,'Password Owner','Owner',(select id from public.positions where erp_role_code='owner'),'Test','owner','password.owner.test@gmail.com','test',owner_id||'/photo.png' from pw union all select staff_id,'Password Staff','Sales Staff',(select id from public.positions where erp_role_code='sales'),'Test','sales','password.staff.test@gmail.com','test',staff_id||'/photo.png' from pw;
insert into auth.sessions(id,user_id,created_at,updated_at) select owner_session,owner_id,clock_timestamp(),clock_timestamp() from pw union all select staff_session,staff_id,clock_timestamp(),clock_timestamp() from pw;
insert into public.device_sessions(id,profile_id,device_fingerprint_hash,device_label,started_at,last_seen_at) select owner_session,owner_id,extensions.digest(owner_session::text,'sha256'),'Owner test',clock_timestamp(),clock_timestamp() from pw union all select staff_session,staff_id,extensions.digest(staff_session::text,'sha256'),'Staff test',clock_timestamp(),clock_timestamp() from pw;
select set_config('request.jwt.claims',jsonb_build_object('sub',owner_id,'role','authenticated','session_id',owner_session)::text,true) from pw;
select ok(not has_function_privilege('service_role','private.finish_password_change_record(uuid,boolean)','execute'),'service cannot bypass proof wrapper');
select ok(not has_table_privilege('authenticated','private.password_provider_receipts','select'),'provider receipts remain private');
set constraints all immediate;
select throws_ok($$update auth.users set encrypted_password='unauthorized' where id=(select staff_id from pw)$$,'42501','Governed password operation required','direct provider password mutation denied');
update pw set operation=(public.prepare_password_change(staff_id,'Receipt regression')->>'operation')::uuid;
select set_config('request.jwt.claims','{"role":"service_role"}',true);
select throws_ok($$select public.finish_password_change(operation,true) from pw$$,'P0001','Provider outcome does not match committed receipt','success cannot be forged without receipt');
update auth.users set raw_app_meta_data=jsonb_build_object('erp_password_operation',(select operation from pw)) where id=(select staff_id from pw);
select ok(not public.password_provider_applied((select operation from pw)),'metadata-only change is not password proof');
-- Actual provider order: password first, metadata later, deferred check at commit.
set constraints all deferred;
update auth.users set raw_app_meta_data='{}' where id=(select staff_id from pw);
update auth.users set encrypted_password='synthetic-provider-1' where id=(select staff_id from pw);
select ok(not public.password_provider_applied((select operation from pw)),'uncommitted password event has no receipt yet');
update auth.users set raw_app_meta_data=jsonb_build_object('erp_password_operation',(select operation from pw)) where id=(select staff_id from pw);
set constraints all immediate;
select ok(public.password_provider_applied((select operation from pw)),'deferred check accepts final marker after password update');
select throws_ok($$update auth.users set encrypted_password='replay' where id=(select staff_id from pw)$$,'42501','Password operation already applied','same operation cannot apply password twice');
select throws_ok($$select public.finish_password_change(operation,false) from pw$$,'P0001','Provider outcome does not match committed receipt','committed provider outcome cannot be marked failed');
select public.finish_password_change(operation,true) from pw;
select ok((select not password_change_pending from public.profiles where id=(select staff_id from pw)),'receipt-backed completion clears target fence');
-- A verified recovery retry supersedes a running Owner password operation.
select set_config('request.jwt.claims',jsonb_build_object('sub',owner_id,'role','authenticated','session_id',owner_session)::text,true) from pw;
update pw set operation=(public.prepare_password_change(owner_id,'Owner interrupted self-change')->>'operation')::uuid;
insert into private.owner_recovery_codes(owner_id,code_hash,version) select owner_id,decode(repeat('a',64),'hex'),1 from pw;
select set_config('request.jwt.claims','{"role":"service_role"}',true);
create temporary table recovery_retry(op uuid);
insert into recovery_retry select (public.begin_owner_recovery('password.owner.test@gmail.com',repeat('a',64))->>'operation')::uuid;
select is((select status from private.password_change_operations where id=(select operation from pw)),'superseded','verified recovery supersedes interrupted Owner password change');
select throws_ok($$update auth.users set encrypted_password='late-old-password',raw_app_meta_data=jsonb_build_object('erp_password_operation',(select operation from pw)) where id=(select owner_id from pw)$$,'42501','Password operation is no longer current','late superseded provider write is rejected');
update auth.users set encrypted_password='synthetic-recovery-1',raw_app_meta_data=jsonb_build_object('erp_password_operation',(select op from recovery_retry)) where id=(select owner_id from pw);
select public.finish_owner_recovery(op,true) from recovery_retry;
select ok((select not recovery_pending and not password_change_pending from public.profiles where id=(select owner_id from pw)),'verified recovery clears both fences');
select is((select count(*)::integer from public.audit_events where action='Password operation superseded' and entity_id=(select owner_id::text from pw)),1,'superseded operation retained in audit');
select * from finish();
rollback;
